### ISSUE TITLE
There is a part not being multilingualized

### ISSUE THREAD

**Issue by mizunashi** [saleemrashid/nem-trezor-standalone#2]
src/index.html Line 67

BUTTON_DOWNLOAD_WALLET  is not transited, it is displayed as it is.
![2018-01-04 14 42 22](https://user-images.githubusercontent.com/1645189/34552032-3b1bea40-f162-11e7-8def-61448a9db60f.png)

**Comment by saleemrashid** [comment]
Thanks for reporting!

Fixed in 1bcfba3c9ae405fc4e5eee0944ffa25815725e7f.
